services:
  - type: web
    name: tailortalk-frontend
    env: python
    buildCommand: pip install -r pyproject.toml
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: DATABASE_URL
        sync: false
    
  - type: web
    name: tailortalk-backend
    env: python
    buildCommand: pip install -r pyproject.toml
    startCommand: cd backend && python main.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: DATABASE_URL
        sync: false